// json_scan.h — just enough JSON to read pokeruby's own data files.
//
// WHAT THIS IS FOR, and what it deliberately is not:
//
//   The decomp describes its maps in three JSON files — data/layouts/layouts.json
//   (every layout's size and tilesets), data/maps/<Name>/map.json (a map's
//   layout and its connections) and data/maps/map_groups.json (the directory
//   list). They are machine-generated by Porymap, so they are regular, small,
//   and never hostile.
//
//   That is the whole requirement. This is a recursive-descent reader for the
//   JSON grammar with no schema, no streaming, no comments extension and no
//   performance ambitions. It exists so the studio can open ANY map straight
//   from the decomp without a pre-bake step — which a generated manifest would
//   have cost us the moment we wanted a map nobody had baked yet.
//
//   Vendoring a header-only parser would also have worked. This is ~200 lines
//   we own against a third-party file in someone else's repository, and the
//   project's standing posture is zero new dependencies.
//
// OBJECTS ARE TWO PARALLEL VECTORS, not a vector<pair<string, Value>>.
//   Value contains its own children, so at the point of declaration it is an
//   incomplete type. C++17 guarantees std::vector tolerates that; it makes no
//   such promise for std::pair, whose members must be complete when the pair is
//   instantiated. Two vectors sidestep the question entirely.
//
//   Lookup is therefore linear. The largest object here has a dozen keys and
//   the largest array about a thousand elements, so it does not matter.

#pragma once

#include <string>
#include <vector>

namespace vr {
namespace json {

struct Value {
    enum class Type { Null, Bool, Number, String, Array, Object };

    Type        type = Type::Null;
    bool        boolean = false;
    double      number = 0.0;
    std::string string;

    std::vector<Value>       items;   // Array
    std::vector<std::string> keys;    // Object, parallel to `values`
    std::vector<Value>       values;

    // Member lookup. Returns nullptr when this is not an object or the key is
    // absent, so callers can chain a miss into a default rather than branching
    // on the type first.
    const Value* find(const char* key) const;

    // Typed accessors that answer with `def` rather than failing, because every
    // caller here is reading a field it already knows the shape of and a
    // missing one is a data problem to report at a higher level.
    const char* as_str(const char* def = "") const;
    int         as_int(int def = 0) const;

    bool is_array()  const { return type == Type::Array; }
    bool is_object() const { return type == Type::Object; }
};

// Parse `path` into `out`. Returns false and reports the byte offset on a
// syntax error, which is the only diagnostic worth having for generated files:
// if these ever fail to parse, the file changed shape rather than being subtly
// wrong.
bool parse_file(const char* path, Value* out);

}  // namespace json
}  // namespace vr
